name: Announce Schema Update

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  announce-update:
    name: Announce Schema Update to bioenergy.org repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: bioenergy-research-centers
          repo: bioenergy.org
          title: 'Update to new version of BRC Schema: ${{ github.event.release.name }}'
          body: |
            A new schema update ( ${{ github.event.release.name }} ) has been made.
            Please review the changes and update this repo accordingly.
            Release notes:
            ${{ github.event.release.body }}
